/**
 * Represents a response from an agent execution platform.
 */
class AgentResponse {
    /**
     * @param {string}responseText - The textual response generated by the agent.
     * @param {object} [details] - Optional details about the agent's execution.
     * @param {string} [details.intent] - The identified intent of the user.
     * @param {Array<object>} [details.actionsTaken] - A list of actions the agent performed.
     * @param {Error} [error] - Any error that occurred during processing.
     */
    constructor(responseText, details = {}, error = null) {
        if (typeof responseText !== 'string') {
            // Allow null or undefined if there was an error and no response text
            if (error && (responseText === null || typeof responseText === 'undefined')) {
                // This is acceptable, responseText can be null/undefined if there's an error
            } else {
                throw new Error('responseText is required and must be a string, or null/undefined if an error occurred.');
            }
        }
        this.responseText = responseText;
        this.details = details; // e.g., { intent, actionsTaken, confidenceScore }
        this.error = error;
    }
}

module.exports = AgentResponse; 